### ISSUE TITLE
Create requirements.txt 

### ISSUE THREAD

**Issue by mayank26saxena** [CuriousLearner/GeeksForGeeksScrapper#7]
Create a requirements.txt file for installing dependencies.

**Comment by CuriousLearner** [comment]
Oh, seems like I just forgot to add it in the repo. 

Also wonder, without `requirements.txt`, why there are so many stars on the repo

Anyway, I'll add one soon. Thanks!

**Comment by arpit1997** [comment]
Agrees to @mayank26saxena requirements will ease users into running this script.
A sample requirements file will be like this.
` ` `
BeautifulSoup

requests
` ` `
And also make a separate directory named src for your main script, It will make your project follow global standards

**Comment by CuriousLearner** [comment]
@arpit1997 since it is just a single script, I don't think there is a need for `src` directory. If the project grows, then we can look into it.
